#!/usr/bin/env python3
"""
Evidence Ingestion Script for CS 660 Project 3 Report
Processes evidence files and generates LaTeX figure includes and reference tables
"""
import os
import sys
import shutil
import hashlib
import re
from pathlib import Path
from typing import Dict, List, Tuple

# Configuration
SCREENSHOTS_DIR = Path("../screenshots")
REPORT_DIR = Path(".")
FIGURES_DIR = REPORT_DIR / "appendix/figures"


def calculate_file_hash(filepath: Path) -> str:
    sha256_hash = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()[:16]
    except Exception:
        return "unknown"


def create_figure_caption(filename: str) -> str:
    base = Path(filename).stem.replace("_", " ")
    return re.sub(r"\s+", " ", base).strip().title()


def process_screenshots() -> List[Dict]:
    if not SCREENSHOTS_DIR.exists():
        print(f"Error: Screenshots directory {SCREENSHOTS_DIR} not found")
        sys.exit(1)

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    images: List[Dict] = []

    label_overrides: Dict[str, str] = {
        # Offline tasks
        "06_linux_passwd_file_contents.png": "fig:A-task0-pvd-analysis",
        "01_john_ripper_cracked_passwords_summary.png": "fig:A-task1-tool-comparison",
        "15_john_windows7_complete_10_passwords_cracked.png": "fig:A-task2-win7-results",
        "09_ophcrack_cracked_passwords_results.png": "fig:A-task3-win2003-ophcrack",
        "17_john_linux_sha512_matrix123_cracked.png": "fig:A-task4-linux-john",
        # Comparison
        "13_morpheus_hash_cross_platform_analysis.png": "fig:A-task5-comparison",
        # Web auth
        "21_hydra_html_form_tripsine_password_found.png": "fig:A-web-html-results",
        "20_hydra_http_basic_auth_sotalait_password_found.png": "fig:A-web-basic-results",
        "22_hydra_digest_auth_hakkis_password_found.png": "fig:A-web-digest-results",
    }

    for filepath in sorted(SCREENSHOTS_DIR.iterdir(), key=lambda p: p.name.lower()):
        if filepath.suffix.lower() not in {".png", ".jpg", ".jpeg", ".pdf"}:
            continue
        dest_path = FIGURES_DIR / filepath.name
        try:
            shutil.copy2(filepath, dest_path)
        except Exception as e:
            print(f"Warning: Could not copy {filepath}: {e}")
            continue

        label = label_overrides.get(filepath.name)
        images.append(
            {
                "filename": filepath.name,
                "caption": create_figure_caption(filepath.name),
                "label": label
                or f"fig:A-misc-{Path(filepath.name).stem.lower().replace(' ', '-').replace('_', '-')}",
                "extension": filepath.suffix.lower(),
            }
        )

    return images


def generate_figures_autogen(figures: List[Dict]) -> None:
    content: List[str] = []
    content.append("% Auto-generated screenshot figures (Appendix only)")
    content.append("% DO NOT EDIT - Generated by scripts/ingest_evidence.py")
    content.append("")

    for fig in figures:
        content.append("\\begin{figure}[H]")
        content.append("    \\centering")
        width = "0.9" if fig["extension"] == ".pdf" else "0.9"
        content.append(
            f"    \\includegraphics[width={width}\\textwidth]{{{fig['filename']}}}"
        )
        content.append(f"    \\caption{{{fig['caption']}}}")
        content.append(f"    \\label{{{fig['label']}}}")
        content.append("\\end{figure}")
        content.append("")

    output_file = REPORT_DIR / "appendix/figures_autogen.tex"
    with open(output_file, "w") as f:
        f.write("\n".join(content))

    print(f"Generated {output_file} with {len(figures)} screenshot figures")


def generate_appendix_index(figures: List[Dict]) -> None:
    content: List[str] = []
    content.append("% Screenshot inventory table")
    content.append("\\begin{longtable}{@{}p{6cm}p{8cm}@{}}")
    content.append(r"\toprule")
    content.append(r"\textbf{Filename} & \textbf{Reference Label} \\")
    content.append(r"\midrule")
    content.append(r"\endfirsthead")
    content.append(r"\toprule")
    content.append(r"\textbf{Filename} & \textbf{Reference Label} \\")
    content.append(r"\midrule")
    content.append(r"\endhead")

    for fig in figures:
        filename = fig["filename"].replace("_", "\\_")
        label = fig["label"].replace("_", "\\_")
        content.append(f"{filename} & \\texttt{{{label}}} \\")

    content.append("\\bottomrule")
    content.append("\\end{longtable}")

    output_file = REPORT_DIR / "sections/A0_appendix_index.tex"
    with open(output_file, "w") as f:
        f.write("\n".join(content))

    print(f"Generated {output_file} with {len(figures)} screenshot entries")


def generate_traceability_table(figures: List[Dict]) -> None:
    # Build quick lookup from label to confirm existence
    existing_labels = {fig["label"] for fig in figures}

    rows = [
        (
            "3.7.1.0",
            "PVD file analysis for Windows 7, 2003, and Linux systems",
            "fig:A-task0-pvd-analysis",
        ),
        (
            "3.7.1.1",
            "Tool comparison: Ophcrack, John, Hashcat advantages",
            "fig:A-task1-tool-study",
        ),
        ("3.7.1.2", "Windows 7 password cracking results", "fig:A-task2-win7-results"),
        (
            "3.7.1.3",
            "Windows 2003 password cracking results",
            "fig:A-task3-win2003-results",
        ),
        ("3.7.1.4", "Linux password cracking results", "fig:A-task4-linux-results"),
        (
            "3.7.1.5",
            "Security comparison of three PVD systems",
            "fig:A-task5-comparison",
        ),
        (
            "3.7.2.1",
            "HTML form authentication password recovery",
            "fig:A-web-html-results",
        ),
        (
            "3.7.2.2",
            "HTTP Basic authentication password recovery",
            "fig:A-web-basic-results",
        ),
        (
            "3.7.2.3",
            "HTTP Digest authentication password recovery",
            "fig:A-web-digest-results",
        ),
        ("3.7.3", "RSA token authentication analysis", None),
    ]

    content: List[str] = []
    content.append("% Traceability table mapping deliverables to screenshots")
    content.append("{\\small")
    content.append("\\begin{longtable}{@{}p{1.8cm}p{9.8cm}p{3.2cm}@{}}")
    content.append("\\caption{Traceability Matrix}\\label{tab:traceability}\\\\")
    content.append("\\toprule")
    content.append(r"\textbf{Task ID} & \textbf{Deliverable} & \textbf{Evidence Reference} \\")
    content.append(r"\midrule")
    content.append(r"\endfirsthead")
    content.append(r"\toprule")
    content.append(r"\textbf{Task ID} & \textbf{Deliverable} & \textbf{Evidence Reference} \\")
    content.append(r"\midrule")
    content.append(r"\endhead")

    for task_id, deliv_text, ref_label in rows:
        deliv_text = deliv_text.replace('&', '\\&').replace('_', '\\_')
        if ref_label and ref_label in existing_labels:
            content.append(fr"{task_id} & {deliv_text} & \ref{{{ref_label}}} \\")
        else:
            content.append(fr"{task_id} & {deliv_text} & N/A \\")

    content.append("\\bottomrule")
    content.append("\\end{longtable}")
    content.append("}")

    output_file = REPORT_DIR / "tables/t_traceability.tex"
    output_file.parent.mkdir(exist_ok=True)
    with open(output_file, "w") as f:
        f.write("\n".join(content))

    print(f"Generated {output_file}")


def main():
    print("CS 660 Project 3 Evidence Ingestion")
    print("====================================")

    print("Processing screenshots only...")
    figures = process_screenshots()
    print(f"Found {len(figures)} screenshots")

    generate_figures_autogen(figures)
    generate_appendix_index(figures)
    generate_traceability_table(figures)

    print("\nEvidence ingestion complete (screenshots only)!")
    print(f"- Copied {len(figures)} screenshots to appendix/figures/")
    print("- Generated figures_autogen.tex")
    print("- Generated A0_appendix_index.tex")
    print("- Generated t_traceability.tex")
    print("\nReady for LaTeX build!")


if __name__ == "__main__":
    os.chdir(Path(__file__).parent.parent)
    main()
